### ISSUE TITLE
Add best practices for writing addins

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Home#16]
We somehow should write down some guidelines and best practices for creating addins. Not sure if this repo or the main cake repo is the best place.

Possible points to add there:
* Cake version against which addins should be build (as low as possible is better than latest)
* Add dependency on Cake package or not?
* How to declare dependencies between addins?
* How to handle required references (Costura or ILMerge)
* ...

**Comment by gep13** [comment]
I think this would be a great initiative.  Given the number of addin's that are in this organisation, I think this would be the best place to keep this information, as we could point to examples in this organisation where some of the above are done.
