### ISSUE TITLE
Outdated statistics in Status.md

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Home#41]
There are some statistics at the top of `Status.md` which may or may not be up-to-date and may not be in line with the statistics automatically calculated by the "Audit" process. For instance, Stus.md says there are 217 addins but the audit process has discovered 219 addins.

I suggest we remove the stats from Status.md and replace it with a link to the audit report.

**Comment by gep13** [comment]
I have no objections to this, in fact, I will go and do that just now.

**Comment by gep13** [comment]
@Jericho why is there such a big difference between the audited number of addins in the cake-contrib organisation?  110 to 68?

**Comment by gep13** [comment]
@Jericho I know we can't get it yet, but the one piece of missing information in the audit summary would be the cake-contrib user on NuGet.org

**Comment by gep13** [comment]
Done.

**Comment by Jericho** [comment]
Regarding package owner: I have a [issue on hold](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/9) to remind me to add this information when the necessary improvement is made to the nuget API. 

Regarding number of transferred addins : I use the following [logic](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/7) to determine if add-in has been transferred. Does that match your logic?

**Comment by gep13** [comment]
So, I think it should match, yes.

Basically, I was getting the number that I had from the number of repositories in the Organisation here:

https://github.com/cake-contrib

Which is currently at 118.  Could it be that some of the links in the status page need to be updated, or perhaps (better) the links in the yml files need to be updated?

**Comment by Jericho** [comment]
Yes indeed: if the project link does not look like `http://github.com/cake-contrib/<project-name>` it will not be considered to be under the cake-contrib organization.

**Comment by gep13** [comment]
@Jericho okay, so I think we need to take a task to ensure that all those links are correct.  Could you raise an issue on the Cake website repo, and here?

**Comment by Jericho** [comment]
To confirm your suspicion, I looked at one example of an addin that was in `Addin.md` but is marked as "not being transferred to cake-contrib" by the audit tool. Sure enough, the [Repository property](https://github.com/cake-build/website/blob/develop/addins/Cake.AndroidAppManifest.yml#L5) in the yaml file is a link to the repo under the original author

**Comment by Jericho** [comment]
Done: https://github.com/cake-build/website/issues/515

**Comment by Jericho** [comment]
The number of addins that were listed in addin.md: 118
The number of addins marked as "transfered to cake-contrib" by the audit tool: 68
Difference between these two numbers: 50

This leads me to conclude there are roughly 50 yml files with an incorrect `Repository` property.

**Comment by gep13** [comment]
Okay, so I think I see why there is such a big difference.

There are a number of addin's that don't yet have yaml files created...

Cake.PinNuGetDependency
Cake.WindowsAppStore
Cake.Markdownlint
Cake.Graph
Cake,Eazfuscator.Net
Cake.Grunt
Cake.Email.Common
Cake.Bower
Cake.Karma
Cake.Issues.Reporting
Cake.Issues.Reporting.Generic
Cake.Mage
Cake.Netlify
Cake.Markdown-Pdf
Cake.ServiceFabric
Cake.ScheduledTasks
Cake.EventLog
Cake.SignClient
Cake.OpenVsixSignTool

Then, there are some addin's in the cake-contrib organisation that are no longer being used:

Cake.Prca.Issues.Markdownlint
Cake.Prca.Issues.EsLint
Cake.Prca.PullRequests.Tfs
Cake.Prca.Issues.DocFx
Cake.Prca.Issues.InspectCode
Cake.Prcs.Issues.MsBuild
Cake.Prca
Cake.Prca.Website
Cake.Prca.Issues.Stylelint
Cake.Prca.Issues.TSLint

And then of course, there are modules:

Cake.Chocolatey.Module
Cake.DotEnv.Module
Cake.DNF.Module
Cake.LongPath.Module
Cake.Npm.Module

I have updated the yaml files that currently do exist in the website to point to the correct location.

**Comment by Jericho** [comment]
Excellent. The audit tool will run on schedule in an hour or so. Your improvements will most certainly make a big difference.

**Comment by gep13** [comment]
Yip, that new number looks a lot better, and I think the remaining can be explained, and we can correct it.
