### ISSUE TITLE
New addin Cake.MkDocs

### ISSUE THREAD

**Issue by michalkowal** [cake-contrib/Home#42]
Hi cake-contrib team.

I'm currently working on new addin for cake - Cake.MkDocs (https://github.com/michalkowal/Cake.MkDocs).
MkDocs create static documentation from Markdowns (https://www.mkdocs.org/).

Addin development is right in progress and there is no working version at the moment.
So I wanted to ask, first of all to add my project to "Status" as WIP.

About movement of repository, we will discuss when I done all pending activities in project 😃

**Comment by gep13** [comment]
@michalkowal that is great news!  Please feel free to create a PR to add an entry into the WIP section.

I am not in a position to do this just now, but if I get a minute later, and I haven't seen a PR, I will get it added.

> About movement of repository, we will discuss when I done all pending activities in project 😃

There is no requirement for the addin to be "finished" before moving the repository.  If this is something that you want to do as an end goal, we can easily do it before being finished.  But it is totally up to you.

Thanks for contributing to the Cake community.
