### ISSUE TITLE
Update guidelines document

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Home#49]
The guidelines document hasn't been updated in a long time and needs to be refreshed. The document should reflect the recommendations that the Cake.AddinDiscoverer is audittting.

I am volunteering to submit a PR with updated guidelines document but I will need help with one specific topic: we should explain why we are recommending `netstandard2.0`.

**Comment by Jericho** [comment]
Calling on @gep13 , @devlead , @mholo65 for input.

**Edit**: also calling on input from @patriksvensson, @agc93 , @pascalberger and any other cake contributor. I'm sorry for not mentioning you, didn't mean to exclude anybody :flushed:

**Comment by Jericho** [comment]
I intend to document the following recommendations in the guidelines document:
- ~~Make sure your addin is listed in Status.md in the cake-contrib repo~~
- Make sure there is a YAML file for your addin in the cake-build web site
- Reference the appropriate Cake.Core and/or Cake.Common nuget packages (0.28.0 at the moment)
- References should be private
- Use the cake-contrib icon. Also explain that it's better to use the CDN url rather than the github rawcontent url.
- Target netstandard2.0, no need to multi-target
- (optional) Transfer your addin's source project to the cake-contrib github organization

Any other suggestions?

**Comment by gep13** [comment]
The status.md is really an interim measure, I don't see it being a requirement.  Rather, the inclusion of the yml file in the website is the primary aim.  I would also like to put in there that the cake-contrib user be added as a co-maintainer of the package on NuGet.org.  I know that you don't have a way to test this just now, but perhaps a note about it to remind people, stating that you can't verify whether this has been done or not.

Regarding the netstandard2.0, I personally think that this is a good recommendation, and it is the way that things are going.  There are times when cross-compiling to an earlier framework is needed, so things have to be taken on a per case basis.

As @mholo65 mentioned in another issue:

> Previously, before moving to dotnet core 2, the only way to support both cake and cake.coreclr was to multitarget (net46 and netstandard1.6). Nowadays there’s (in most cases) no real need to multitarget, but many addins still do (mainly because they did it earlier).

**Comment by patriksvensson** [comment]
@Jericho I wasn't called on for input, but it looks good to me 👍

**Comment by agc93** [comment]
Agreed, these seem like they would make things a bit clearer. :+1:

**Comment by Jericho** [comment]
@gep13 how about I mention that the audit process currently uses Status.md in the cake-contrib repo (in addition to the YAML files on the web site) but this list will eventually be abandoned since it's maintained manually which is a burdensome and error prone process.

**Comment by Jericho** [comment]
@patriksvensson and @agc93 : sorry guys, didn't mean to exclude you. I, of course, welcome your feedback!!!

**Comment by pascalberger** [comment]
LGTM 👍

**Comment by devlead** [comment]
LGTM 👍

**Comment by gep13** [comment]
>@Jericho said...
how about I mention that the audit process currently uses Status.md in the cake-contrib repo (in addition to the YAML files on the web site) but this list will eventually be abandoned since it's maintained manually which is a burdensome and error prone process.

Sounds good to me.

**Comment by bjorkstromm** [comment]
LGTM!

@gep13 said
> I would also like to put in there that the cake-contrib user be added as a co-maintainer of the package on NuGet.org. I know that you don't have a way to test this just now

@jericho if I’ll show you how to do this using NuGet V3 api, would you mind adding it to your audit script?

**Comment by gep13** [comment]
https://github.com/cake-build/website/issues/529

**Comment by Jericho** [comment]
@mholo65 I don't mind at all. In fact I'm really curious because last I checked, the nuget API did not provided ownership information. I even opened a [feature request](https://github.com/NuGet/NuGetGallery/issues/5647)

**Comment by bjorkstromm** [comment]
@jericho, sorry. I thought it was possible to query, but after a little investigation I noticed that it wasn’t (just like you did :smile:). Ownership seems to be NuGet Gallery specific, and not part of the NuGet V3 protocol. Hope they’ll provide a way to do this.

**Comment by Jericho** [comment]
PR created. Looking forward to comments and suggestions.
