### ISSUE TITLE
Update guidelines to not suggest rawgit urls

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Home#59]
Considering rawgit.com is in shutdown mode, and is requesting everyone to stop using it (mentioned on website).
It would probably be in the best of interest to update the guidelines with a different way to add icon urls.

There is a few mentions of alternatives on the rawgit.com website:
- [jsDelivr](https://www.jsdelivr.com/rawgit) (Personally tested, and offers same functionality as rawgit, **I suggest this one**)
- [GitHub Pages](https://pages.github.com/)
- [CodeSandbox](https://codesandbox.io/)
- [unpkg](https://unpkg.com/)

**Comment by pascalberger** [comment]
See https://github.com/cake-contrib/Home/pull/58

**Comment by AdmiringWorm** [comment]
ah, should have known something already existed.

I forgot to check the PR section before opening the issue.


Perhaps just close this one then?

**Comment by pascalberger** [comment]
I'm would suggest to keep this open and close when guidelines are updated. I've updated the PR accordingly
