### ISSUE TITLE
Delete outdated Status.md

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Home#61]
This [file](https://github.com/cake-contrib/Home/blob/master/Status.md) used to be regularly manually updated but it hasn't been in over a year and the information is outdated. For the most part, the information that used to be maintained in this file has been replaced with a report automatically generated twice a day by Cake.AddinDiscoverer.

For all these reasons, I suggest deleting this file.

**Comment by gep13** [comment]
This was deleted here: https://github.com/cake-contrib/Home/commit/228c26f3f6c9fb2035dd0469b4b51eb85734a85d
