### ISSUE TITLE
Audits are missing many addins

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Home#68]
In https://github.com/cake-contrib/Home/blob/ec5310225ab81bcabd7ef7c38e421916808b78d4/Audit_for_Cake_0.33.0.md (that's the last run from 2020-11-14) all addins were still listed, at https://github.com/cake-contrib/Home/blob/952aa07eee1af9be03cb0892e68c803c48b22b05/Audit_for_Cake_0.33.0.md (that's the first run from 2020-11-15) most addins are gone. 

`Audit.xlsx` also shows lot of errors since that commit.

**Comment by gep13** [comment]
@nils-a thanks for catching this.  I suspect that we may need to move this issue to the [AddinDiscoverer repo](https://github.com/cake-contrib/Cake.AddinDiscoverer) but lets bring @Jericho into this issue for visibility.

**Comment by Jericho** [comment]
Thanks @nils-a for catching this. It looks like our build has been failing with an error from GitHub. I'll investigate.

**Comment by gep13** [comment]
@nils-a I am going to go ahead and close this issue out, as there is another issue tracking this in the AddinDiscoverer repository.
